@echo off
echo 🗑️ Deleting node_modules...
rmdir /s /q node_modules
echo 🗑️ Deleting .next...
rmdir /s /q .next
echo 🗑️ Deleting package-lock.json...
del package-lock.json
echo 📦 Reinstalling dependencies...
npm install
echo 🔧 Generating Prisma client...
npx prisma generate
echo 🗄️ Running migrations...
npx prisma migrate dev --name init
echo 🌱 Seeding database...
npx prisma db seed
echo ✅ Build complete! Run 'npm run dev' to start the server.