"use client";

import Link from "next/link";
import { ChevronLeft } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-white to-gray-50">
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Back Button */}
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-gray-500 hover:text-[#FF6B35] font-medium text-sm mb-8 group transition-colors"
        >
          <div className="w-8 h-8 rounded-lg bg-gray-100 group-hover:bg-[#FF6B35]/10 flex items-center justify-center transition-colors">
            <ChevronLeft className="w-4 h-4" />
          </div>
          Back to Home
        </Link>

        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex justify-center mb-4">
            <img src="/nthoppa-logo.png" alt="Nthoppa" className="h-12 w-auto" />
          </div>
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Disclaimer
          </h1>
          <p className="text-gray-500">
            Last updated: May 2026
          </p>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8 md:p-12 space-y-6">
          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">General Information Only</h2>
            <p className="text-gray-600 leading-relaxed">
              The information provided on the Nthoppa platform is for general informational purposes only. It does not constitute financial advice, investment advice, or any other form of professional advice. You should not rely on this information as a substitute for direct consultation with qualified financial professionals.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">No Financial Advice</h2>
            <p className="text-gray-600 leading-relaxed">
              Nthoppa (Pty) Ltd does not provide financial advice. Any tools, calculators, recommendations, or insights generated by our platform are based on algorithms and the information you provide. These are for educational and informational purposes only and should not be considered personalised financial advice.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Investment Risks</h2>
            <p className="text-gray-600 leading-relaxed">
              All investments carry risk, and past performance is not indicative of future results. You may lose some or all of your invested capital. You should carefully consider your financial situation, risk tolerance, and investment objectives before making any investment decisions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Insurance Products</h2>
            <p className="text-gray-600 leading-relaxed">
              Insurance products offered through NthoppaSure are underwritten by licensed insurance partners. Coverage, terms, and conditions are subject to the policy documents provided by the underwriter. Premiums and coverage amounts are estimates until a formal policy is issued.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">No Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              To the fullest extent permitted by law, Nthoppa (Pty) Ltd disclaims all liability for any loss or damage arising from your use of our platform, services, or any information provided. This includes direct, indirect, incidental, consequential, or punitive damages.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Regulatory Status</h2>
            <p className="text-gray-600 leading-relaxed">
              Nthoppa operates in compliance with the laws of the Republic of Botswana. However, some financial products or services may not be suitable or available in all jurisdictions. It is your responsibility to ensure compliance with applicable laws in your location.
            </p>
          </div>

          <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg">
            <p className="text-sm text-amber-800">
              <strong>Important:</strong> This disclaimer is for informational purposes only. For complete legal information, please contact our support team at info@nthoppa.com.
            </p>
          </div>
        </div>

        {/* Contact Section */}
        <div className="mt-8 text-center">
          <a
            href="mailto:info@nthoppa.com"
            className="inline-flex items-center justify-center px-6 py-3 bg-[#FF6B35] text-white font-semibold rounded-xl hover:bg-[#e55a2b] transition-colors"
          >
            Contact Support for Full Details
          </a>
        </div>

        {/* Footer */}
        <div className="text-center mt-8 pt-6 border-t border-gray-200">
          <p className="text-xs text-gray-400">
            Nthoppa (Pty) Ltd | info@nthoppa.com | +267 75 736 600
          </p>
          <p className="text-xs text-gray-400 mt-2">
            © 2026 Nthoppa Financial Technologies. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}